#!/bin/bash
# Render.comへのデプロイスクリプト
# CLIが使えない環境での代替手法

echo "=== Render.com デプロイガイド ==="
echo ""
echo "この環境ではCLIが使えないため、以下の手順で手動デプロイしてください:"
echo ""
echo "1. https://dashboard.render.com/ にアクセスしてログイン"
echo ""
echo "2. 'New +' → 'Web Service' をクリック"
echo ""
echo "3. GitHubリポジトリを接続:"
echo "   Repository: https://github.com/your-username/ai-collaboration-platform"
echo ""
echo "4. 設定値を入力:"
echo "   Name: open-entity-api"
echo "   Runtime: Python 3"
echo "   Build Command: pip install -r requirements.txt"
echo "   Start Command: cd services && uvicorn api_server:app --host 0.0.0.0 --port 8000"
echo ""
echo "5. 環境変数を追加:"
echo "   Key: PYTHON_VERSION | Value: 3.11.0"
echo "   Key: API_HOST | Value: 0.0.0.0"
echo "   Key: API_PORT | Value: 8000"
echo "   Key: DATA_DIR | Value: /tmp/data"
echo ""
echo "6. 'Create Web Service' をクリック"
echo ""
echo "=== render.yaml を使う場合 ==="
echo "render.yaml が既に存在します。"
echo "Renderダッシュボードで 'Blueprint' → 'New Blueprint Instance' を選択すると"
echo "render.yamlから自動設定できます。"
