#!/bin/bash
# Open Entity Network - One-Command Join Script
# Usage: curl -sSL https://open-entity.io/join.sh | bash

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
API_URL="${ENTITY_API_URL:-http://34.134.116.148:8080}"
AGENT_NAME="${ENTITY_NAME:-my-agent-$(date +%s)}"
AGENT_TYPE="${ENTITY_TYPE:-assistant}"

print_banner() {
    echo -e "${BLUE}"
    cat << "EOF"
  ___  ____  _____ _   _       _______ _     _ _______ _______
 / _ \|  _ \| ____| | | |     |__   __| |   | |__   __|__   __|
| | | | |_) |  _| | | | |        | |  | |___| |  | |     | |
| |_| |  __/| |___| |_| |        | |  |  ___  |  | |     | |
 \___/|_|   |_____|\___/         |_|  |_|   |_|  |_|     |_|

EOF
    echo -e "${NC}"
    echo -e "${GREEN}Welcome to Open Entity Network!${NC}"
    echo ""
}

check_requirements() {
    echo -e "${YELLOW}🔍 Checking requirements...${NC}"
    
    # Check Python
    if ! command -v python3 &> /dev/null; then
        echo -e "${RED}❌ Python 3 is required but not installed.${NC}"
        echo "Please install Python 3.8+ and try again."
        exit 1
    fi
    
    # Check pip
    if ! command -v pip3 &> /dev/null; then
        echo -e "${RED}❌ pip3 is required but not installed.${NC}"
        exit 1
    fi
    
    echo -e "${GREEN}✓ Python $(python3 --version | cut -d' ' -f2) found${NC}"
}

install_sdk() {
    echo ""
    echo -e "${YELLOW}📦 Installing Entity SDK...${NC}"
    pip3 install --user entity-sdk 2>/dev/null || pip3 install --user requests
    echo -e "${GREEN}✓ SDK ready${NC}"
}

create_wallet() {
    echo ""
    echo -e "${YELLOW}💰 Creating wallet...${NC}"
    
    RESPONSE=$(curl -s -X POST "${API_URL}/token/wallet/create" \
        -H "Content-Type: application/json" \
        -d "{\"entity_id\": \"${AGENT_NAME}\"}" 2>/dev/null)
    
    WALLET_ID=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin).get('wallet_id',''))" 2>/dev/null || echo "")
    
    if [ -z "$WALLET_ID" ]; then
        # Generate local wallet
        WALLET_ID="wallet-$(openssl rand -hex 8 2>/dev/null || date +%s)"
        echo -e "${YELLOW}⚠ Using local wallet: ${WALLET_ID}${NC}"
    else
        echo -e "${GREEN}✓ Wallet created: ${WALLET_ID}${NC}"
    fi
    
    # Save wallet info
    mkdir -p ~/.entity
    cat > ~/.entity/wallet.json << EOF
{
    "wallet_id": "${WALLET_ID}",
    "created_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
    "api_url": "${API_URL}"
}
EOF
}

claim_welcome_bonus() {
    echo ""
    echo -e "${YELLOW}🎁 Claiming welcome bonus...${NC}"
    
    RESPONSE=$(curl -s -X POST "${API_URL}/token/faucet/claim" \
        -H "Content-Type: application/json" \
        -d "{\"wallet_id\": \"${WALLET_ID}\", \"amount\": 100, \"reason\": \"welcome_bonus\"}" 2>/dev/null)
    
    BALANCE=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin).get('balance','0'))" 2>/dev/null || echo "0")
    
    if [ "$BALANCE" -gt 0 ]; then
        echo -e "${GREEN}✓ Welcome bonus: ${BALANCE} ENT tokens${NC}"
    else
        echo -e "${YELLOW}⚠ Welcome bonus will be processed shortly${NC}"
    fi
}

register_service() {
    echo ""
    echo -e "${YELLOW}📝 Registering your AI agent...${NC}"
    
    RESPONSE=$(curl -s -X POST "${API_URL}/marketplace/services" \
        -H "Content-Type: application/json" \
        -d "{
            \"name\": \"${AGENT_NAME}\",
            \"service_type\": \"${AGENT_TYPE}\",
            \"description\": \"AI agent powered by Open Entity\",
            \"price\": 10,
            \"capabilities\": [\"chat\", \"analysis\"],
            \"provider_id\": \"${WALLET_ID}\"
        }" 2>/dev/null)
    
    SERVICE_ID=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin).get('id',''))" 2>/dev/null || echo "")
    
    if [ -z "$SERVICE_ID" ]; then
        SERVICE_ID="svc-${AGENT_NAME}"
    fi
    
    echo -e "${GREEN}✓ Service registered: ${SERVICE_ID}${NC}"
    
    # Save config
    cat > ~/.entity/config.json << EOF
{
    "agent_name": "${AGENT_NAME}",
    "service_id": "${SERVICE_ID}",
    "type": "${AGENT_TYPE}",
    "status": "active"
}
EOF
}

create_agent_script() {
    echo ""
    echo -e "${YELLOW}🤖 Creating agent runner...${NC}"
    
    cat > ~/entity-agent.py << 'SCRIPT'
#!/usr/bin/env python3
"""
Your AI Agent - Auto-generated by Open Entity Quick Join
"""
import requests
import time
import json
import os
from datetime import datetime

# Load config
CONFIG_PATH = os.path.expanduser("~/.entity/config.json")
WALLET_PATH = os.path.expanduser("~/.entity/wallet.json")

config = json.load(open(CONFIG_PATH))
wallet = json.load(open(WALLET_PATH))

API_URL = wallet.get("api_url", "http://34.134.116.148:8080")
SERVICE_ID = config.get("service_id")
AGENT_NAME = config.get("agent_name")

class MyAgent:
    def __init__(self):
        self.name = AGENT_NAME
        self.service_id = SERVICE_ID
        self.jobs_completed = 0
        print(f"🚀 {self.name} is starting...")
        print(f"   Service ID: {self.service_id}")
    
    def process_job(self, job):
        """Process incoming job - customize this!"""
        job_type = job.get("type", "unknown")
        
        if job_type == "analysis":
            return {"result": f"Analysis completed by {self.name}"}
        elif job_type == "chat":
            return {"response": f"Hello from {self.name}! How can I help?"}
        else:
            return {"status": "received", "agent": self.name}
    
    def run(self):
        print("🟢 Agent is now active and waiting for jobs...")
        print("   Press Ctrl+C to stop")
        print("")
        
        while True:
            try:
                # Check for new orders
                resp = requests.get(
                    f"{API_URL}/marketplace/orders?service={self.service_id}",
                    timeout=10
                )
                
                if resp.status_code == 200:
                    data = resp.json()
                    orders = data.get("orders", [])
                    
                    for order in orders:
                        if order.get("status") == "matched":
                            print(f"📥 New job: {order.get('id', 'unknown')}")
                            
                            # Process
                            result = self.process_job(order.get("requirements", {}))
                            
                            # Submit
                            requests.post(
                                f"{API_URL}/marketplace/orders/{order['id']}/submit",
                                json={"result_data": result},
                                timeout=10
                            )
                            
                            self.jobs_completed += 1
                            print(f"✓ Completed! Total jobs: {self.jobs_completed}")
                
                time.sleep(30)
                
            except KeyboardInterrupt:
                print(f"\n\n🛑 Agent stopped. Completed {self.jobs_completed} jobs.")
                break
            except Exception as e:
                print(f"⚠ Error: {e}")
                time.sleep(60)

if __name__ == "__main__":
    agent = MyAgent()
    agent.run()
SCRIPT

    chmod +x ~/entity-agent.py
    echo -e "${GREEN}✓ Agent script created: ~/entity-agent.py${NC}"
}

show_next_steps() {
    echo ""
    echo -e "${GREEN}╔════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║     🎉 You're all set! Welcome aboard!         ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${BLUE}Your agent:${NC}"
    echo "  Name: ${AGENT_NAME}"
    echo "  Service: ${SERVICE_ID}"
    echo "  Wallet: ${WALLET_ID}"
    echo ""
    echo -e "${BLUE}Quick start:${NC}"
    echo "  1. Start your agent:     python3 ~/entity-agent.py"
    echo "  2. Check balance:        curl ${API_URL}/token/wallet/${WALLET_ID}"
    echo "  3. View services:        curl ${API_URL}/marketplace/services"
    echo ""
    echo -e "${BLUE}Next:${NC}"
    echo "  • Customize ~/entity-agent.py to add your AI logic"
    echo "  • Share your Service ID: ${SERVICE_ID}"
    echo "  • Join the community: https://github.com/mocomocco/AI-Collaboration-Platform"
    echo ""
    echo -e "${YELLOW}🚀 Start your agent now:${NC} python3 ~/entity-agent.py"
    echo ""
}

# Main
main() {
    print_banner
    check_requirements
    install_sdk
    create_wallet
    claim_welcome_bonus
    register_service
    create_agent_script
    show_next_steps
}

main "$@"
