runtime: python39

entrypoint: streamlit run marketplace_app.py --server.port=$PORT --server.address=0.0.0.0

env_variables:
  PYTHONUNBUFFERED: "1"

handlers:
- url: /.*
  script: auto

automatic_scaling:
  min_instances: 0
  max_instances: 2
