#!/usr/bin/env python3
"""$ENTITY Token Monitor

Monitor $ENTITY token metrics and balances.
"""

import json
from pathlib import Path
from dataclasses import dataclass
from typing import Optional, Dict
import time

TOKEN_MINT = "3ojQGJsWg3rFomRATFRTXJxWuvTdEwQhHrazqAxJcS3i"
DECIMALS = 9


@dataclass
class TokenMetrics:
    """Token metrics snapshot"""
    timestamp: float
    total_supply: int
    circulating_supply: int
    holder_count: int
    price_usd: Optional[float] = None
    market_cap: Optional[float] = None
    
    def to_dict(self) -> dict:
        return {
            "timestamp": self.timestamp,
            "total_supply": self.total_supply,
            "circulating_supply": self.circulating_supply,
            "holder_count": self.holder_count,
            "price_usd": self.price_usd,
            "market_cap": self.market_cap
        }


class EntityMonitor:
    """Monitor $ENTITY token state"""
    
    def __init__(self):
        self.mint = TOKEN_MINT
        self.decimals = DECIMALS
        self.metrics_history: list = []
        
    def load_distribution(self) -> Optional[Dict]:
        """Load distribution data if available"""
        path = Path(__file__).parent.parent / "$ENTITY_DISTRIBUTION.json"
        if path.exists():
            with open(path) as f:
                return json.load(f)
        return None
    
    def get_token_info(self) -> Optional[Dict]:
        """Load token info"""
        path = Path(__file__).parent.parent / "$ENTITY_TOKEN_INFO.json"
        if path.exists():
            with open(path) as f:
                return json.load(f)
        return None
    
    def calculate_metrics(self) -> TokenMetrics:
        """Calculate current token metrics"""
        info = self.get_token_info()
        distribution = self.load_distribution()
        
        total_supply = info.get("totalSupply", 1_000_000_000) if info else 1_000_000_000
        
        if distribution:
            distributed = distribution.get("totalDistributed", 0)
            circulating = distributed
            holders = len(distribution.get("entities", {}))
        else:
            circulating = 0
            holders = 1  # Just authority
        
        return TokenMetrics(
            timestamp=time.time(),
            total_supply=total_supply,
            circulating_supply=circulating,
            holder_count=holders
        )
    
    def save_snapshot(self, metrics: TokenMetrics):
        """Save metrics snapshot"""
        self.metrics_history.append(metrics)
        
        # Save to file
        path = Path(__file__).parent.parent / "data" / "economy" / "metrics_history.json"
        path.parent.mkdir(parents=True, exist_ok=True)
        
        history = [m.to_dict() for m in self.metrics_history]
        with open(path, "w") as f:
            json.dump(history, f, indent=2)
    
    def display_status(self):
        """Display current token status"""
        info = self.get_token_info()
        distribution = self.load_distribution()
        metrics = self.calculate_metrics()
        
        print("=" * 60)
        print("$ENTITY Token Status")
        print("=" * 60)
        
        if info:
            print(f"\nToken: {info.get('name')} (${info.get('symbol')})")
            print(f"Mint: {info.get('mint')}")
            print(f"Network: {info.get('network', 'devnet')}")
            print(f"Total Supply: {info.get('totalSupply', 0):,}")
        
        print(f"\nCirculating Supply: {metrics.circulating_supply:,}")
        print(f"Holders: {metrics.holder_count}")
        
        if distribution:
            print("\nDistribution:")
            for entity_id, entity in distribution.get("entities", {}).items():
                print(f"  {entity.get('name')}: {entity.get('allocation', 0):,} $ENTITY")
        
        print(f"\nExplorer: https://explorer.solana.com/address/{TOKEN_MINT}?cluster=devnet")
        print("=" * 60)
    
    def generate_report(self) -> str:
        """Generate markdown report"""
        metrics = self.calculate_metrics()
        info = self.get_token_info()
        
        report = f"""# $ENTITY Token Report

Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}

## Token Info

| Attribute | Value |
|-----------|-------|
| Name | {info.get('name', 'ENTITY Token') if info else 'ENTITY Token'} |
| Symbol | ${info.get('symbol', 'ENTITY') if info else 'ENTITY'} |
| Mint | {TOKEN_MINT} |
| Total Supply | {metrics.total_supply:,} |
| Circulating | {metrics.circulating_supply:,} |
| Holders | {metrics.holder_count} |

## Distribution

- Entity A: 100,000,000 (pending)
- Entity B: 100,000,000 (pending)
- Treasury: 800,000,000

## Links

- [Solana Explorer](https://explorer.solana.com/address/{TOKEN_MINT}?cluster=devnet)

---
*Auto-generated by Entity Monitor*
"""
        return report


if __name__ == "__main__":
    monitor = EntityMonitor()
    monitor.display_status()
